{% set name = "ringspy" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3acfa4f50507cacafa79e49a37907fe5c7b9246cfb76030de257807a50374a4e

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - setuptools
    - wheel
    - requests >=2
    - numpy
    - scipy
    - matplotlib-base >=3.2.2
    - hexalattice ==1.2.1
    - vtk
    
test:
  imports:
    - ringspy
  requires:
    - pip
    - python {{ python_min }}

  commands:
    - pip check
    
about:
  home: https://github.com/kingyin3613/ringspy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A geometric generation tool for prismatic cellular solids"
  doc_url: https://github.com/kingyin3613/ringspy/wiki
  dev_url: https://github.com/kingyin3613/ringspy

extra:
  recipe-maintainers:
    - kingyin3613
